<?php
/**
 * @file
 * Contains d8_custom_block.module.
 */

/**
 * Implements hook_theme().
 */
function d8_custom_block_theme($existing, $type, $theme, $path) {
  return [
    'weather-service' => [
      'variables' => [
        'weather_data' => [
					'city' => NULL,
          'temp_min' => NULL,
          'temp_max' => NULL,
          'pressure' => NULL,
          'humidity' => NULL,
          'wind' => [
						'speed' => NULL,
          ],
        ],
      ],
		],
  ];
}